---
# tasks file for roles/osp-instance-delete
- name: remove an instance
  os_server:
    name: "{{ item.value.name }}"
    state: absent
    wait: true
    timeout: 300
  with_dict: "{{ osp_servers }}"