---
# tasks file for roles/osp-instance-delete
- name: remove an instance
  os_server:
    name: "{{ item }}"
    state: absent
    wait: true
    timeout: 300
  loop:
    - frontend
    - app1
    - app2
    - db