- hosts: tag_instance_filter_three_tier_app_mbetti_redhat_com
  gather_facts: false
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"
#  - name: Copy open_three-tier-app.repo
#    copy:
#      src: open_three-tier-app.repo
#      dest: /etc/yum.repos.d/open_three-tier-app.repo
#      mode: 0644
#    become: true
