- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: workstation-896d.rhpds.opentlc.com
       group: workstation

- hosts: workstation
  become: yes
  roles:
    - osp-servers
