- hosts: frontends
  gather_facts: false
  tasks:
  - name: Smoke test AWS website
    uri:
      url: "http://{{ item }}"
      return_content: yes
    with_items:
      - "{{ inventory_hostname }}"
    register: http_resp
    failed_when: "'Ansible has done its job' not in http_resp.results[0].content"
