- hosts: frontends
  gather_facts: false
  tasks:
  - name: Smoke test AWS website
    command: "http {{item}}"
    with_items:
      - "{{ inventory_hostname }}"
    register: http_resp
    failed_when: "'Ansible has done its job' not in http_resp.stdout"  
  - name: Fail if 'Ansible has done its job' is not in the page content
