---
# tasks file for base-config
- name: Copy internal.repo
  copy:
    src: internal.repo
    dest: /etc/yum.repos.d/internal.repo
    mode: 0644

#- debug: msg="the value of internal.repo is {{lookup('file', '/etc/yum.repos.d/internal.repo') }}"

#- debug: msg="the value of internal.repo is {{lookup('file', '/home/cloud-user/.ssh/authorized_keays') }}"
